#:schema node_modules/wrangler/config-schema.json
name = "hono-remix-adapter-example"
compatibility_date = "2024-11-06"
# main = "./worker.ts"
# assets = { directory = "./build/client" }
pages_build_output_dir = "./build/client"

[vars]
EXAMPLE_VARIABLE = "REINO ATAI!!"
